### ISSUE TITLE
Support AndroidX

### ISSUE THREAD

**Issue by k-kagurazaka** [yshrsmz/simple-preferences#14]
Hi,

I'm using this nice library but I have a trouble with migrating AndroidX.
This library depends on Support Annotation Library and uses the annotations in generated code.
I guess processor use `androidx.annotation.*` instead of `android.support.annotation.*` in AndroidX mode.

**Comment by yshrsmz** [comment]
hi @k-kagurazaka , I've just uploaded v2.0.0 which support AndroidX.
please check it out and let me know if there's any issue. thanks!
