### ISSUE TITLE
Migrate to the latest Android Gradle Plugin

### ISSUE THREAD

**Issue by yshrsmz** [yshrsmz/simple-preferences#16]
we need to migrate to AGP 3.2.0

**Comment by wseemann** [comment]
It appears this project already uses gradle 3.2 per the [build.gradle](https://github.com/yshrsmz/simple-preferences/blob/master/build.gradle), am I missing something?

**Comment by yshrsmz** [comment]
This library is using beta version of the plugin, and stable 3.2 was released already.
